[project]
name = "zerobypass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "klembord>=0.3.0",
    "pytest-playwright>=0.7.2",
    "rich>=14.3.2",
    "setuptools>=80.10.2",
]
[project.scripts]
zerobypass = "src.__main__:main"

[build-system]
requires = ["setuptools>=80.10.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]
